[project]
name="src"
version="0.0.1"
description="An MLOPS project for productionising models"
authors = [{name = "Agniva Chakravarty", email = "agnivac11@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}

